export const OFFERS_ACTION_TYPES = {
  FETCH_OFFERS_START: 'category/FETCH_OFFERS_START',
  FETCH_OFFERS_SUCCESS: 'category/FETCH_OFFERS_SUCCESS',
  FETCH_OFFERS_FAILED: 'category/FETCH_OFFERS_FAILED',
};
