export const USER_ACTION_TYPES = {
  REGISTRATION_START: 'user/REGISTRATION_START',
  REGISTRATION_SUCCESS: 'user/REGISTRATION_SUCCESS',
  REGISTRATION_FAIL: 'user/REGISTRATION_FAIL',
  LOGIN_START: 'user/LOGIN_START',
  LOGIN_SUCCESS: 'user/LOGIN_SUCCESS',
  LOGIN_FAIL: 'user/LOGIN_FAIL',
  LOGOUT: 'user/LOGOUT',
};
